[build]
    command = "GATSBY_CONCURRENT_DOWNLOAD=25 yarn workspace gatsby-plugin-schemajson-i18n build"
  	functions = "gatsby-plugin-schemajson-i18n/src/api"
    publish = "gatsby-plugin-schemajson-i18n/public"

[build.environment]
  NODE_VERSION = "18.12.1"

[[plugins]]
  package = "@netlify/plugin-gatsby"

[[plugins]]
  package = "@netlify/plugin-local-install-core"
